import * as Yup from "yup";

export const initialValues = {
  firstname: "",
  middlename: "",
  lastname: "",
  suffix: "",
  age: "",
  contact: "",
  email: "",
  address: "",
  city: "",
  birthdate: "",
  birthplace: "",
  sex: "male",
  citizenship: "",
  educational_background: "Elementary",
  civil_status: "single",
  applicant_status: "qualified",
  application_status: "screening",
  application_notes: "",
  isRequirementComplete: 1,
  religion: "",
};

export const validationSchema = Yup.object().shape({
  firstname: Yup.string().required("First Name is required"),
  middlename: Yup.string().required("Middle Name is required"),
  lastname: Yup.string().required("Last Name is required"),
  suffix: Yup.string().notRequired(),
  age: Yup.string().required("Age is required"),
  contact: Yup.string().required("Contact is required"),
  email: Yup.string().required("Email is required"),
  address: Yup.string().required("Address is required"),
  city: Yup.string().required("City is required"),
  birthdate: Yup.string().required("Birthdate is required"),
  birthplace: Yup.string().required("Birthplace is required"),
  sex: Yup.string().required("Sex is required"),
  citizenship: Yup.string().required("Citizenship is required"),
  educational_background: Yup.string().required("Education is required"),
  civil_status: Yup.string().required("Civil Status is required"),
  applicant_status: Yup.string().required("Employment Status is required"),
  application_status: Yup.string().required("Employment Status is required"),
  application_notes: Yup.string().notRequired(),
  isRequirementComplete: Yup.string().required("Req Status is required"),
  religion: Yup.string().required("Religion is required"),
});
